### PR TITLE
20240329 edit basload trace

### PR DESCRIPTION
**Pull request by stefan-b-jakobsson**

### CODE REVIEW

**Comment by stefan-b-jakobsson** [comment]
There might be something not right here still. While running the editor, I can't see any source code being displayed anywhere for bank 13.

**Comment by mooinglemur** [comment]
somehow this causes the resulting `rom_lst.h` to end up with this on line 229388:

```c
/* $FFF0 */ "NATURE\"\n.byt \"basload\", appversion_major, appversion_minor, appversion_patch",
```

Which looks like it truncated the line that said `.segment "SIGNATURE"`

**Comment by stefan-b-jakobsson** [comment]
I fixed the truncating issue affecting only segment selection lines.

**Comment by stefan-b-jakobsson** [comment]
I revisited this code from March. It looks like the output is correct after the fix on March 30.

**Review by mooinglemur — APPROVED** [review]

**Pull request merged**
