### PR TITLE
Adding Central European/Eastern Latin/Slavic Latin/Romanian character set (iso-8859-16)

### PR DESCRIPTION
**Pull request by adiee5**
After Cyrillic charset was approved, I thought about adding a charset for central European Latin. and since Cyrillic charsets got compressed, It could nicely fit in the space, that Cyrillic occupied few commits ago. 

I've decided to go with iso-16 code page. This is essentially just iso-15 but some characters are replaced with letters, that are useful in central European languages. This way, it could be easier to incorporate it into existing Unicode conversions and in general it provides a better data integrity in the commander x16 ecosystem, that if we went with iso-2. The only drawback compared to iso-2 (except of course popularity) is that iso-16 doesn't support Czech or Slovak (which on its own is a big drawback).

Preview:
image
image

A table with chars, that are actually different from iso-15 (potential room for more drastic compression?)
image

Todo:
- [x] come up with an internal name for the charset (pls help)
- [x] Add the logic thing

### CODE REVIEW

**Comment by adiee5** [comment]
Ok, i did come up with a name, it's now ready to be merged

**Comment by Fulgen301** [comment]
> This is essentially just iso-15 but some characters are replaced with letters, that are useful in central European languages. 

Might be worth compressing the ISO charsets even further at some point so that all the characters that always stay the same aren't duplicated multiple times.

**Comment by adiee5** [comment]
> Might be worth compressing the ISO charsets even further at some point so that all the characters that always stay the same aren't duplicated multiple times.

Yes! This would be very nice, if it's possible. I even included a table, that shows which chars are actually different from ISO-15

**Review by mooinglemur — APPROVED** [review]

**Comment by adiee5** [comment]
Nice!

**Pull request merged**
