### PR TITLE
[KERNAL/GRAPH] relocate VARFONTS to B0

### PR DESCRIPTION
**Pull request by mooinglemur**
Given that GEOS is gone, and the font library for conio doesn't get much use, the RAM area for the font routines has been relocated to bank 0.  Any calls that touch the font library in the GRAPH bank have been wrapped in KVARS_START / KVARS_END to preserve the caller RAM bank and set the RAM bank to 0 when called from the KERNAL API

This is part of the effort to free up low RAM to make room for 65C816 vector and trampoline support.

### CODE REVIEW

**Comment by stefan-b-jakobsson** [comment]
My first test without analyzing any of the code changes indicates that there is a problem calling the GRAPH_clear function ($ff23). But I need to continue testing tomorrow.

**Comment by stefan-b-jakobsson** [comment]
I've got the following observations:

- This change will break any program that has used the graph bank vectors directly, as there was previously no requirement to select RAM bank before calling the functions. I don't know if there are any such programs.
- If the change is done like this, we should document in the graph bank code which functions require the caller to first set RAM bank 0.
- I think the change breaks GRAPH_clear and GRAPH_set_window, as they use some of the VARFONTS variables without RAM bank 0 first being selected.
- It's difficult to guarantee there will be no side effects of the change, but probably it's good if the two above mentioned functions are fixed.

**Comment by mooinglemur** [comment]
Do you think we should preserve the bank from within the GRAPH bank? This might be better in terms of layering, but I don't want to unnecessarily double-preserve if one call chains to another.  This is mainly why I decided to do it at the API entry point in bank 0 rather than in the GRAPH bank itself.

**Comment by mooinglemur** [comment]
> I think the change breaks GRAPH_clear and GRAPH_set_window, as they use some of the VARFONTS variables without RAM bank 0 first being selected.
I'll wrap the calls to those two functions now, which should solve this particular problem.

**Comment by mooinglemur** [comment]
I think it'd be better since KVARS_START / KVARS_END __can__ indeed be nested, to wrap the functions themselves that use variables.  I will make that change today.

**Comment by stefan-b-jakobsson** [comment]
> I think it'd be better since KVARS_START / KVARS_END **can** indeed be nested, to wrap the functions themselves that use variables. I will make that change today.

OK. Maybe it's a bit safer to do that. If you change your mind, and want to go with the first solution, I'm OK with that as well.

**Comment by Fulgen301** [comment]
> This is part of the effort to free up low RAM to make room for 65C816 vector and trampoline support.

FYI - with #266 merged, there actually is enough space for all 65C816-related features - I haven't looked at the MONITOR too closely yet, but the only parts of the trampoline that have to be in low RAM are the ones that restore the ROM / RAM bank, which the MONITOR currently uses the BASIC line buffer for and which the 65C816 MONITOR trampoline should be able to continue doing with just a few more bytes used (of which there are plenty free in the line buffer).

So while freeing up 38 bytes of precious low RAM space is always great, it is not critical for the 65C816 support, so it doesn't stress at all, especially if it has a chance of breaking real-world usages,.

**Comment by stefan-b-jakobsson** [comment]
I'll approve this, as I think it's working correctly now.

**Review by stefan-b-jakobsson — APPROVED** [review]

**Pull request merged**
