### PR TITLE
Fetching PS/2 data more quickly

### PR DESCRIPTION
**Pull request by stefan-b-jakobsson**
Querying the SMC for key codes or mouse packets takes relatively long time even if there is no data to fetch. The SMC is queried once every VBLANK. The query for both key codes and mouse packet takes about 560 us if there is no data available, which is about 3.2% of the VBLANK.

The intention is to speed up the data fetch considerably.

The SMC is made to respond to three different slave addresses:

- 0x42: This is the current slave address, and it will be left unchanged. An older Kernal can still query this slave address for key codes and mouse packets.
- 0x43: This is a dedicated slave address that only returns key codes. It doesn't require a command or offset. As soon as the SMC has received the start condition + the slave address + R/W bit, it responds with the next available key code. If no key code is available, it ignores (NACKs) the request.
- 0x44: This is a dedicated slave address that only returns mouse packets. It works the same way a address 0x43.

I haven't measured the speed improvement, but I reckon that querying the SMC if no data exists will be about 70 us, an improvement of 210 us per query.

Fetching a key code should be around 140 us, cutting the time in half compared to the current situation.

Fetching a 4-byte mouse packet should be 350 us compared to 490 us today.

This change is still interesting if the X16 in the future has the ability to signal data available to the Kernal with IRQ or NMI, as it cuts down the transmission time when there is data to fetch.

A corresponding PR is made for the SMC firmware.

If these changes are merged, the user needs to update the SMC firmware before (or at the same time) as he or she updates Kernal.  If we bump the SMC version when adding this change, it would be possible for the Kernal to check the SMC version and query 0x42 if the user has on older SMC firmware version.

### CODE REVIEW

**Review by AndyMt — COMMENTED** [review]
Code changes do what's intended and follow the style of the existing code. 
Remark on coding style for comments: other code blocks align comments on a certain column (30? but also not consistent). 
Maybe agree on a way of doing comments.

**Comment by stefan-b-jakobsson** [comment]
The SMC part of this change had to be reworked, as it is not future proof to use more than one I2C slave address. The ATtiny861 handles multiple slave addresses just fine, but that is probably not the case if it's replaced by some other MCU in the future, such as ESP32.

The new implementation is based on the following:

- The SMC only responds to slave address 0x42
- If you read from the SMC without first setting a command offset number, the SMC returns the value of a default read operation
- After power on, this default read operation returns a key code
- It is possible to change what read operation is the default one by sending a command to the SMC
- There is a command that returns a combination of a key code and a mouse packet, intended to be used when the mouse is enabled

The new implementation is equally fast or in some cases faster than the first implementation.

**Comment by mooinglemur** [comment]
I would be more comfortable merging this change if it had a fallback to the existing method so that this update doesn't have the SMC update as a hard dependency

**Comment by stefan-b-jakobsson** [comment]
> I would be more comfortable merging this change if it had a fallback to the existing method so that this update doesn't have the SMC update as a hard dependency

I think it could only be done if the Kernal reads the SMC version on boot, and uses that information to decide whether to fetch data the old or the new way.

**Comment by stefan-b-jakobsson** [comment]
The code was changed to support older SMC firmware as well:
- If the SMC firmware version is < 47.0.0, then key codes and mouse movement is fetched the old way
- Otherwise key codes and mouse movement is fetched the new faster way

**Review by mooinglemur — APPROVED** [review]

**Pull request merged**
